# buildspec.yml
version: 0.2

phases:

  # install:
  #   commands:
  #     - command

  pre_build:
    commands:
      # - xcodebuild -list -project I\ am\ Groot.xcodeproj
      - xcodebuild clean

  build:
    commands:
      - xcodebuild build -scheme "I am Groot" -sdk iphoneos -destination generic/platform=iOS

  # post_build:
  #   commands:
  #     - path

# artifacts:
#   name: getting-started-$(date +%Y-%m-%d).ipa
#   files:
#     - 'getting started.ipa'
#   base-directory: 'code/build-release'

# cache:
#   paths:
#     - 'code/build-release'
